language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm install -g yarn 

script:
  - npm run test # or 'yarn test'
  - npm run build # or 'yarn build'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  local_dir: build
  on:
    branch: main
